- name: Add Docker repo
  get_url:
    url: "{{ docker_repo }}"
    dest: /etc/yum.repos.d/docker-ce.repo
        
- name: Enable Docker Edge & Test repo
  community.general.ini_file:  #ini_file:
    dest: /etc/yum.repos.d/docker-ce.repo
    section: "{{ item }}"
    option: enabled
    value: 0
  with_items: ['docker-ce-test', 'docker-ce-edge']


