---
- name: Install docker on RHEL
  hosts: wordpress
  become: true
  roles:
    - install_docker

- name: Install docker on RHEL
  hosts: wordpress
  become: true
  gather_facts: false
  vars:
     ansible_ssh_private_key_file: "/Users/zhonganqing/.ssh/wca4a-0514.pem"

  roles:
    - install_docker
